label firstDayRoadIntroduction:
    "Es ist ein sonniger Tag draußen, Vögel zwitschern, Blumen blühen..."
    "Und wieso schreiben wir an Tagen wie diesen eine Lateintest?"
    unknown "MAAAAAAAAAAAAAARRRRRRRRRCUUUUUUUUUUUUUUUUUUUUUUUUUUUS!!!"
    "Habe ich schon erwähnt? Ich bin Marcus. Marcus Kashima."
    "Und die, die gerade hinter mir herläuft ist meine Kindheitsfreundin Aki Kuzunoha."
    aki "MAAAAAAAAAAAARRRRRRCUUUUUUUUUUUS warte mal!"
    marcus "Jaja, schon gut."
    "Ich bleibe stehen und drehe mich um."
    aki "*Stöhn* Phew! Ich bin völlig aus der Puste. Bitte warte mal langsamer!"
    marcus "Das macht ja gar kein Sinn!"
    aki "Trotzdem!"
    "Nachdem sie mich endlich aufgeholt hat und sich erholt hat, gehen wir nebeneinander los."
    aki "Hast du dich auf die Lateintest vorbereitet?"
    marcus "Na klar! Ich bin ja schließlich der Leiter vom Lateinclub!"
    "Ach ja, ich bin der stolze Leiter vom Lateinclub an unserer Schule."
    aki "Ich hoffe wir scheiben die Arbeit nicht über ACIs, die kann ich gar nicht!"
    aki "Wofür steht ACI eigentlich überhaupt?"
    marcus "Akkusativus cum Infinitivo."
    marcus "Du solltest das wissen, ich habe dir mehrmals gesagt, dass du das lernen solltest!"
    aki "Ich habe versucht, aber kanns immer nicht!"
    "Wir haben uns dann für den Rest des Schulweges Vokablen abgefragt. Ziemlich normal."
