label firstDayRoadIntroduction:
    "Es ist ein sonniger Tag draußen, Vögel zwitschern, Blumen blühen..."
    "Und wieso schreiben wir an Tagen wie diesen einen Lateintest?"
    unknown "MAAAAAAAAAAAAAARRRRRRRRRCUUUUUUUUUUUUUUUUUUUUUUUUUUUS!!!"
    "Habe ich schon erwähnt? Ich bin Marcus. Marcus Kashima."
    "Und die, die gerade hinter mir herläuft ist meine Kindheitsfreundin Aki Kuzunoha."
    aki "MAAAAAAAAAAAARRRRRRCUUUUUUUUUUUS warte mal!"
    marcus "Jaja, schon gut."
    "Ich bleibe stehen und drehe mich um."
    # roughly descripe akis looks and personality
    aki "*Stöhn* Phew! Ich bin völlig aus der Puste. Bitte warte mal langsamer!"
    marcus "Das macht ja gar kein Sinn!"
    aki "Trotzdem!"
    "Nachdem sie mich endlich aufgeholt hat und sich erholt hat, gehen wir nebeneinander los."
    "Aki wohnt ein paar Blöcke hinter mir, und eigentlich wäre der Plan, dass sie zuerst losgeht, und dass sie dann vor unserer Tür wartet, bis ich fertig bin."
    "Aber anscheinend klappt das nicht so ganz."
    aki "Hast du dich auf die Lateintest vorbereitet?"
    marcus "Na klar! Ich bin ja schließlich der Leiter vom Lateinclub!"
    "Ach ja, ich bin der stolze Leiter vom Lateinclub an unserer Schule."
    "Der Lateinclub wurde von der vorletzten Schüler-generation gegründet, und ich bin seit dem letzten Jahr Präsident vom Club."
    "Wir sind eine recht aktive Gruppe mit recht vielen Mitgliedern, nähmlich 14."
    aki "Ich hoffe wir scheiben den Test nicht über ACIs, die kann ich gar nicht!"
    aki "Wofür steht ACI eigentlich überhaupt?"
    marcus "Akkusativus cum Infinitivo."
    marcus "Du solltest das wissen, ich habe dir mehrmals gesagt, dass du das lernen solltest!"
    aki "Ich habe versucht, aber kanns immer nicht!"
    "Wir haben uns dann für den Rest des Schulweges Vokablen abgefragt. Ziemlich normal."
